import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import { createViewportState, panViewport, zoomViewportAt } from "../editor-renderer.js";
import { buildMinimapData, createMinimapProjection, minimapMapPolygon, minimapPointToGrid, minimapSceneBounds, projectViewport, viewportScenePolygon, MINIMAP_BIN_COUNT, MINIMAP_LAYER_ORDER } from "../editor-minimap.js";

function doc(){return{fixedRanges:[{id:"fr",kind:"blocked",color:"#ff0000",cells:[[0,0],[2,2]]}],ranges:[{id:"ur",kind:"allowed",color:"#00ff00",cells:[[4,4]]}],fixedBuildings:[{id:"fb",name:"Fixed label",typeId:"ft",x:6,y:6,width:2,height:2}],buildings:[{id:"ub",name:"User label",typeId:"type-01",x:8,y:8,width:1,height:1}]}}
test("minimap module exposes canonical layer order",()=>assert.deepEqual(MINIMAP_LAYER_ORDER,["fixedRanges","userRanges","fixedBuildings","userBuildings","viewport"]));
test("whole map projection fits inside the canvas",()=>{const p=createMinimapProjection(230,160),points=minimapMapPolygon().map(x=>p.sceneToMini(...x));for(const[x,y]of points){assert.ok(x>=0&&x<=230);assert.ok(y>=0&&y<=160)}});
test("map geometry is an isometric parallelogram",()=>{const points=minimapMapPolygon();assert.equal(points.length,4);assert.notEqual(points[0][0],points[1][0]);assert.notEqual(points[0][1],points[3][1])});
test("fixed and user ranges retain separate render data and semantics",()=>{const data=buildMinimapData(doc());assert.equal(data.rangeMarks.filter(x=>x.fixed).length,2);assert.equal(data.rangeMarks.filter(x=>!x.fixed).length,1);assert.ok(data.rangeMarks.some(x=>x.kind==="blocked"&&x.color==="#ff0000"));assert.ok(data.rangeMarks.some(x=>x.kind==="allowed"&&x.color==="#00ff00"))});
test("fixed and user buildings are separate and labels are excluded",()=>{const data=buildMinimapData(doc());assert.equal(data.fixedBuildings.length,1);assert.equal(data.userBuildings.length,1);assert.equal(data.fixedBuildings[0].width,2);assert.equal("name" in data.fixedBuildings[0],false)});
test("viewport outline uses the actual visible scene corners",()=>{const state=createViewportState({centerX:20,centerY:20,zoom:1,width:800,height:500}),points=viewportScenePolygon(state);assert.equal(points.length,4);assert.ok(points[0][0]<points[2][0]);assert.ok(points[0][1]<points[2][1]);assert.equal(projectViewport(state,createMinimapProjection(230,160)).length,4)});
test("pan immediately changes projected viewport position",()=>{const p=createMinimapProjection(230,160),a=createViewportState({centerX:20,centerY:20,zoom:1,width:800,height:500}),b=panViewport(a,100,0);assert.notDeepEqual(projectViewport(a,p),projectViewport(b,p))});
test("zoom changes viewport outline size",()=>{const p=createMinimapProjection(230,160),a=createViewportState({centerX:20,centerY:20,zoom:1,width:800,height:500}),b=zoomViewportAt(a,2,400,250);const width=x=>Math.abs(projectViewport(x,p)[1][0]-projectViewport(x,p)[0][0]);assert.ok(width(b)<width(a))});
test("resize changes viewport outline size",()=>{const p=createMinimapProjection(230,160),a=createViewportState({centerX:20,centerY:20,zoom:1,width:400,height:300}),b={...a,width:800,height:600};assert.notDeepEqual(projectViewport(a,p),projectViewport(b,p))});
test("minimap click projection maps back to a valid grid cell",()=>{const p=createMinimapProjection(230,160),point=p.sceneToMini(0,0),grid=minimapPointToGrid(...point,p);assert.deepEqual(grid,[0,0])});
test("range cache bins large cell collections",()=>{const cells=[];for(let y=0;y<1024;y+=2)for(let x=0;x<512;x+=2)cells.push([x,y]);const data=buildMinimapData({...doc(),fixedRanges:[],ranges:[{kind:"allowed",color:"#123456",cells}]});assert.equal(data.sourceCounts.rangeCells,131072);assert.ok(data.rangeMarks.length<=MINIMAP_BIN_COUNT*MINIMAP_BIN_COUNT);assert.ok(data.rangeMarks.length<data.sourceCounts.rangeCells)});
test("1000 buildings remain a linear compact collection",()=>{const buildings=Array.from({length:1000},(_,i)=>({id:String(i),name:"Ignored",typeId:"type-01",x:i%512,y:i%1024,width:1,height:1})),data=buildMinimapData({...doc(),fixedBuildings:[],buildings});assert.equal(data.userBuildings.length,1000);assert.equal(data.sourceCounts.buildings,1000)});
test("minimap state is not part of canonical map bounds or documents",()=>{const bounds=minimapSceneBounds();assert.equal("collapsed" in bounds,false);assert.equal("viewport" in doc(),false)});

const html=fs.readFileSync(new URL("../index.html",import.meta.url),"utf8"),renderer=fs.readFileSync(new URL("../editor-renderer.js",import.meta.url),"utf8"),moduleText=fs.readFileSync(new URL("../editor-minimap.js",import.meta.url),"utf8");
test("editor contains accessible layered minimap canvases and collapse button",()=>{assert.match(html,/id="minimapPanel"/);assert.match(html,/id="minimapToggle"[^>]*aria-expanded/);assert.match(moduleText,/dataCanvas\.id="minimapCanvas"/);assert.match(moduleText,/aria-label/)});
test("click and pointer drag both navigate through main renderer",()=>{assert.match(moduleText,/pointerdown/);assert.match(moduleText,/pointermove/);assert.match(moduleText,/renderer\.centerAtGrid/);assert.match(renderer,/centerAtGrid\(x, y\)/)});
test("editable and shared navigation reuse engine view persistence policy",()=>{assert.match(renderer,/engine\.setView/);assert.match(renderer,/if \(result\.persisted\) editorHost\?\.markDirty/)});
test("data changes and viewport-only redraw are separated",()=>{assert.match(moduleText,/setDocument\(doc\).*invalidate\(true\)/s);assert.match(moduleText,/setViewport\(next\).*invalidate\(false\)/s);assert.match(html,/onDocumentChange/);assert.match(html,/onViewportChange/)});
test("new, saved, shared, import, recovery and mutations remount or notify minimap",()=>{assert.ok((html.match(/mountMapRenderer\(\);/g)||[]).length>=5);assert.match(renderer,/onDocumentChange\(mapDocument\)/)});
test("filter state is deliberately absent from minimap data",()=>{assert.doesNotMatch(moduleText,/buildingFilter|appearance\(/)});
test("theme, ResizeObserver and DPR are handled at runtime",()=>{assert.match(moduleText,/MutationObserver/);assert.match(moduleText,/ResizeObserver/);assert.match(moduleText,/devicePixelRatio/)});
test("collapse is runtime-only and has all four translations",()=>{assert.match(html,/classList\.toggle\("collapsed"/);assert.doesNotMatch(moduleText,/localStorage|sessionStorage|serialize/);for(const lang of ["en","ko","ja","ru"])assert.match(html,new RegExp(`${lang}:\\{title:`))});
test("main renderer remains independent from minimap implementation",()=>{assert.doesNotMatch(renderer,/editor-minimap|minimapCanvas|buildMinimapData/)});
