import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs";
import { PNSMapEngine } from "../editor-engine.js";
import { parseDocument } from "../editor-document.js";
import { convertDocumentToTemplate } from "../../template-editor/template-editor-core.js";
import { parseTemplate } from "../editor-template.js";
import { MAX_ISOMAP_FILE_BYTES, createIsomapDownload, isomapFilename, readIsomapFile } from "../editor-file.js";

function file(text,{size=new TextEncoder().encode(text).length}={}){return {size,async text(){return text}}}
function valid(){PNSMapEngine.createNewDocument({title:"공유 지도"});return PNSMapEngine.exportDocument()}

test("canonical export includes fixed snapshot but excludes runtime and server state",()=>{const raw=valid();raw.fixed_building_types=[{id:"ft",name:"Fixed",color:"#123456",width:1,height:1}];raw.fixed_buildings=[{id:"fb",name:"Base",type_id:"ft",x:0,y:0}];raw.fixed_ranges=[{id:"fr",kind:"allowed",color:"#abcdef",cells:[[2,2]]}];PNSMapEngine.loadDocument(raw);const result=createIsomapDownload(PNSMapEngine,{title:"공유 지도"});assert.equal(result.documentData.fixed_buildings.length,1);for(const key of ["selection","hover","preview","filter","history","dirty","currentMapId","sessionToken","readOnly","linkedTemplateId"])assert.equal(key in result.documentData,false)});
test("Unicode filename is retained and unsafe names fall back safely",()=>{assert.equal(isomapFilename("서울 기지 🗺️"),"서울 기지 🗺️.isomap");assert.equal(isomapFilename("<>:\\/?*"),"map.isomap");assert.equal(isomapFilename("   "),"map.isomap")});
test("export uses the current UI title without mutating the engine",()=>{valid();const before=PNSMapEngine.exportDocument(),out=createIsomapDownload(PNSMapEngine,{title:"새 파일명"});assert.equal(out.documentData.title,"새 파일명");assert.equal(PNSMapEngine.exportDocument().title,before.title)});
test("valid isomap imports and export-import round trip is identical",async()=>{const original=valid(),parsed=await readIsomapFile(file(JSON.stringify(original)));assert.deepEqual(parsed,original);PNSMapEngine.loadDocument(parsed);assert.deepEqual(createIsomapDownload(PNSMapEngine).documentData,original)});
test("legacy isomap without fixed arrays imports with empty fixed snapshot",async()=>{const raw=valid();delete raw.fixed_building_types;delete raw.fixed_buildings;delete raw.fixed_ranges;const parsed=await readIsomapFile(file(JSON.stringify(raw)));assert.deepEqual(parsed.fixed_building_types,[]);assert.deepEqual(parsed.fixed_buildings,[]);assert.deepEqual(parsed.fixed_ranges,[])});
test("file cancellation is a no-op",async()=>assert.equal(await readIsomapFile(null),null));
test("file size limit is 32 MiB and rejects before reading",async()=>{assert.equal(MAX_ISOMAP_FILE_BYTES,32*1024*1024);let read=false;await assert.rejects(()=>readIsomapFile({size:MAX_ISOMAP_FILE_BYTES+1,async text(){read=true;return "{}"}}),e=>e.code==="FILE_TOO_LARGE");assert.equal(read,false)});
test("empty, read failure, and malformed JSON have distinct errors",async()=>{await assert.rejects(()=>readIsomapFile(file("  ")),e=>e.code==="EMPTY_FILE");await assert.rejects(()=>readIsomapFile({size:1,async text(){throw Error("no")}}),e=>e.code==="FILE_READ_FAILED");await assert.rejects(()=>readIsomapFile(file("{")),e=>e.code==="INVALID_JSON")});
test("wrong format, version, and validation errors are classified",async()=>{const raw=valid();await assert.rejects(()=>readIsomapFile(file(JSON.stringify({...raw,format:"pns-map-template"}))),e=>e.code==="WRONG_FORMAT");await assert.rejects(()=>readIsomapFile(file(JSON.stringify({...raw,version:2}))),e=>e.code==="UNSUPPORTED_VERSION");await assert.rejects(()=>readIsomapFile(file(JSON.stringify({...raw,title:""}))),e=>e.code==="INVALID_DOCUMENT")});
test("failed import parsing leaves the currently loaded document untouched",async()=>{const before=valid();await assert.rejects(()=>readIsomapFile(file("{")));assert.deepEqual(PNSMapEngine.exportDocument(),before)});
test("invalid fixed data and occupancy collisions are rejected",async()=>{const raw=valid();raw.fixed_building_types=[{id:"ft",name:"F",color:"#123456",width:1,height:1}];raw.fixed_buildings=[{id:"a",name:"A",type_id:"ft",x:0,y:0},{id:"b",name:"B",type_id:"ft",x:0,y:0}];await assert.rejects(()=>readIsomapFile(file(JSON.stringify(raw))),e=>e.code==="INVALID_DOCUMENT")});

const editorHtml=fs.readFileSync(new URL("../index.html",import.meta.url),"utf8");
test("ordinary editor exposes separated server save and file controls",()=>{assert.match(editorHtml,/id="saveButton"/);assert.match(editorHtml,/id="openMapFileButton"/);assert.match(editorHtml,/id="exportMapFileButton"/);assert.match(editorHtml,/accept="\.isomap"/)});
test("import clears map UUID, resets runtime through renderer mount, and remains server-dirty",()=>{const section=editorHtml.slice(editorHtml.indexOf('openMapFileInput.addEventListener("change"'),editorHtml.indexOf('mapTitleInput.addEventListener'));assert.match(section,/currentMapId = null/);assert.match(section,/mountMapRenderer\(\)/);assert.match(section,/history\?\.clear\(\{ saved: true \}\)/);assert.match(section,/nonHistoryDirty = true/);assert.match(section,/dirty = true/)});
test("read-only permits export and blocks import",()=>{assert.match(editorHtml,/exportMapFileButton\.disabled = !enabled/);assert.match(editorHtml,/openMapFileButton\.disabled = !editable/);assert.match(editorHtml,/if \(!file \|\| readOnly/)});
test("export does not touch dirty state or history save points",()=>{const section=editorHtml.slice(editorHtml.indexOf('exportMapFileButton.addEventListener'),editorHtml.indexOf('openMapFileButton.addEventListener'));assert.doesNotMatch(section,/setDirty|history|markSaved|mutationRevision|currentMapId/)});
test("four languages include open, export, confirmation and file errors",()=>{for(const lang of ["en","ko","ja","ru"]){const start=editorHtml.indexOf(`${lang}: { open:`);assert.ok(start>=0);const part=editorHtml.slice(start,start+900);for(const key of ["open:","export:","confirm:","FILE_READ_FAILED:","UNSUPPORTED_VERSION:"])assert.match(part,new RegExp(key))}});

test("actual fixed-map conversion sample parses and converts through production paths",()=>{const samplePath = new URL(
  "./fixtures/고정맵-변환-샘플.isomap",
  import.meta.url,
);assert.ok(fs.existsSync(samplePath),"actual sample file must exist");const raw=JSON.parse(fs.readFileSync(samplePath,"utf8")),document=parseDocument(raw);assert.equal(document.buildings.length,10);assert.equal(document.buildings[0].typeId,"type-01");assert.equal(document.buildings[0].width,2);assert.deepEqual(document.view,{centerX:39,centerY:41,zoom:0.8695652173913043});const template=parseTemplate(convertDocumentToTemplate(raw));assert.equal(template.fixedBuildingTypes.length,1);assert.equal(template.fixedBuildings.length,10);assert.equal(template.fixedBuildings[0].name,document.buildings[0].name);assert.equal(template.fixedBuildings[0].x,document.buildings[0].x);assert.deepEqual(template.view,document.view)});
