import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs";
import { emptyTemplate } from "../../template-editor/template-editor-core.js";
import { createTemplateAdminClient, validateTemplateNames } from "../../template-editor/template-editor-server.js";

const names={name_ko:"기본 맵",name_en:"Default map",name_ja:"基本マップ",name_ru:"Базовая карта"}, id="123e4567-e89b-12d3-a456-426614174000";
function auth(){return {cleared:0,authorizationHeaders(){return {Authorization:"Bearer admin-token"}},clearToken(){this.cleared++}}}
function response(body,status=200){return {ok:status>=200&&status<300,status,async json(){return body}}}
test("all four metadata names are required and trimmed",()=>{assert.deepEqual(validateTemplateNames({...names,name_ko:" 기본 맵 "}),names);for(const key of Object.keys(names))assert.throws(()=>validateTemplateNames({...names,[key]:""}))});
test("list reuses the admin Bearer session and exposes metadata",async()=>{let request;const client=createTemplateAdminClient({auth:auth(),fetchImpl:async(...args)=>(request=args,response({templates:[{id,...names,is_default:true}]}))});const list=await client.list();assert.equal(request[1].headers.Authorization,"Bearer admin-token");assert.equal(list[0].is_default,true)});
test("create sends only canonical template data and names then links response",async()=>{let body;const client=createTemplateAdminClient({auth:auth(),fetchImpl:async(_u,o)=>(body=JSON.parse(o.body),response({template:{id,...names,is_default:false,updated_at:"now"}},201))});await client.create(names,emptyTemplate());assert.equal(body.action,"create_template");assert.equal(body.template_data.format,"pns-map-template");assert.equal("name_ko" in body.template_data,false);assert.equal(client.state().linkedTemplateId,id);assert.deepEqual(client.state().linkedTemplateNames,names)});
test("invalid client template never sends create request",async()=>{let calls=0;const client=createTemplateAdminClient({auth:auth(),fetchImpl:async()=>{calls++;return response({})}});await assert.rejects(()=>client.create(names,{format:"bad"}));assert.equal(calls,0)});
test("create failure leaves document-owned input and linked state untouched",async()=>{const input=emptyTemplate(),client=createTemplateAdminClient({auth:auth(),fetchImpl:async()=>response({error:"DATABASE_ERROR"},500)});await assert.rejects(()=>client.create(names,input));assert.deepEqual(input,emptyTemplate());assert.equal(client.state().linkedTemplateId,null)});
test("server detail uses canonical parse path and sets linked metadata",async()=>{let url;const client=createTemplateAdminClient({auth:auth(),fetchImpl:async value=>(url=value,response({template:{id,...names,updated_at:"later",template_data:emptyTemplate()}}))});const result=await client.load(id);assert.match(url,/\?id=/);assert.equal(result.templateData.format,"pns-map-template");assert.equal(client.state().linkedUpdatedAt,"later")});
test("invalid server detail does not alter an existing link",async()=>{let count=0;const client=createTemplateAdminClient({auth:auth(),fetchImpl:async()=>++count===1?response({template:{id,...names,template_data:emptyTemplate()}}):response({template:{id:"other",...names,template_data:{format:"bad"}}})});await client.load(id);await assert.rejects(()=>client.load("other"));assert.equal(client.state().linkedTemplateId,id)});
test("replace sends template data without name metadata and retains UUID",async()=>{let body,count=0;const client=createTemplateAdminClient({auth:auth(),fetchImpl:async(_u,o)=>{count++;if(o.method==="GET")return response({template:{id,...names,template_data:emptyTemplate()}});body=JSON.parse(o.body);return response({template:{id,...names,updated_at:"new"}})}});await client.load(id);await client.replace(emptyTemplate());assert.equal(body.action,"replace_template_file");assert.equal(body.id,id);assert.equal("name_ko" in body,false);assert.equal(client.state().linkedTemplateId,id);assert.equal(client.state().linkedUpdatedAt,"new")});
test("replace 404 clears link while other failures retain it",async()=>{let mode=404;const client=createTemplateAdminClient({auth:auth(),fetchImpl:async(_u,o)=>o.method==="GET"?response({template:{id,...names,template_data:emptyTemplate()}}):response({error:"Template not found."},mode)});await client.load(id);await assert.rejects(()=>client.replace(emptyTemplate()));assert.equal(client.state().linkedTemplateId,null);await client.load(id);mode=500;await assert.rejects(()=>client.replace(emptyTemplate()));assert.equal(client.state().linkedTemplateId,id)});
test("401 clears the established admin session",async()=>{const a=auth(),client=createTemplateAdminClient({auth:a,fetchImpl:async()=>response({error:"UNAUTHORIZED"},401)});await assert.rejects(()=>client.list());assert.equal(a.cleared,1)});
test("network errors fail closed without changing linked state",async()=>{const client=createTemplateAdminClient({auth:auth(),fetchImpl:async()=>{throw new Error("offline")}});await assert.rejects(()=>client.list(),error=>error.code==="NETWORK_ERROR");assert.equal(client.state().linkedTemplateId,null)});
test("linked state is runtime-only and canonical export contains no metadata",async()=>{const client=createTemplateAdminClient({auth:auth(),fetchImpl:async()=>response({template:{id,...names,template_data:emptyTemplate()}})});const loaded=await client.load(id);assert.equal("linkedTemplateId" in loaded.templateData,false);assert.equal("name_ko" in loaded.templateData,false)});

const html=fs.readFileSync(new URL("../../template-editor/index.html",import.meta.url),"utf8"),app=fs.readFileSync(new URL("../../template-editor/template-editor-app.js",import.meta.url),"utf8");
test("registration UI has four required names and preserves file workflow",()=>{for(const field of Object.keys(names))assert.match(html,new RegExp(`name="${field}"[^>]*required`));assert.match(html,/accept="\.isotemplate"/);assert.match(html,/accept="\.isomap"/);assert.match(html,/id="exportBtn"/)});
test("server picker shows default badge and supports detail load",()=>{assert.match(html,/serverTemplates/);assert.match(app,/\[기본맵\]/);assert.match(app,/server\.load\(id\)/)});
test("local new, file open, and isomap import clear the server link",()=>{assert.match(app,/function replace\(raw,\{saved=true,clearLink=true\}/);assert.match(app,/if\(clearLink\)server\.clearLink\(\)/);assert.match(app,/newBtn[\s\S]*templateFile[\s\S]*mapFile/)});
test("replace requires explicit snapshot confirmation and has deletion guidance",()=>{assert.match(app,/이미 이 고정맵으로 생성된 기존 사용자 맵은 변경되지 않습니다/);assert.match(app,/더 이상 존재하지 않습니다[\s\S]*다시 등록/)});
test("template editor does not implement rename, delete, default mutation, or secrets",()=>{assert.doesNotMatch(app,/update_template_names|delete_template|set_default_template|SERVICE_ROLE|x-admin-secret/)});
test("ordinary map and editor entry files are unchanged by server integration",()=>{assert.doesNotMatch(fs.readFileSync(new URL("../../index.html",import.meta.url),"utf8"),/template-editor-server/);assert.doesNotMatch(fs.readFileSync(new URL("../index.html",import.meta.url),"utf8"),/template-editor-server/)});
