import test from "node:test"; import assert from "node:assert/strict";
import { createHistory } from "../editor-history.js";
import { parseTemplate } from "../editor-template.js";
import { TemplateEditorEngine, convertDocumentToTemplate, emptyTemplate } from "../../template-editor/template-editor-core.js";
import { createTemplateBuildingController, createTemplateRangeController } from "../../template-editor/template-editor-controllers.js";

const type = { id:"fixed-a", name:"고정", color:"#123456", width:1, height:1 };
function source({ buildings=[], ranges=[], fixed_building_types=[], fixed_buildings=[], fixed_ranges=[] }={}) { return {format:"isometric-map-editor",version:1,title:"새 문서",map:{min_x:0,max_x:511,min_y:0,max_y:1023},building_types:Array.from({length:7},(_,i)=>({id:`type-${String(i+1).padStart(2,"0")}`,name:`T${i+1}`,color:"#123456"})),buildings,ranges,fixed_building_types,fixed_buildings,fixed_ranges,view:{center_x:39,center_y:41,zoom:.8695652173913043}}; }

test("new template has empty fixed collections and no ordinary types",()=>{const e=new TemplateEditorEngine();assert.equal(e.getDocument().fixedBuildingTypes.length,0);assert.equal(e.getDocument().buildingTypes.length,0)});
test("fixed type CRUD and in-use protection",()=>{const e=new TemplateEditorEngine();e.addType(type);e.editType(type.id,{name:"변경",color:"#abcdef",width:2,height:2});assert.equal(e.getDocument().fixedBuildingTypes[0].name,"변경");e.addBuilding({name:"A",typeId:type.id,x:3,y:3});assert.throws(()=>e.deleteType(type.id));e.deleteBuilding(e.getDocument().fixedBuildings[0].id);e.deleteType(type.id);assert.equal(e.getDocument().fixedBuildingTypes.length,0)});
test("fixed type validates size, name and color",()=>{const e=new TemplateEditorEngine();assert.throws(()=>e.addType({...type,width:1,height:2}));assert.throws(()=>e.addType({...type,name:""}));assert.throws(()=>e.addType({...type,color:""}))});
test("fixed building placement, bounds, collision, move, edit and delete",()=>{const e=new TemplateEditorEngine();e.addType(type);const a=e.addBuilding({name:"A",typeId:type.id,x:0,y:0});assert.throws(()=>e.addBuilding({name:"B",typeId:type.id,x:0,y:0}));assert.throws(()=>e.moveBuilding(a.id,-1,-1));e.moveBuilding(a.id,2,2);e.editBuilding(a.id,{name:"B"});assert.equal(e.getDocument().fixedBuildings[0].name,"B");e.deleteBuilding(a.id);assert.equal(e.getDocument().fixedBuildings.length,0)});
test("2x2 fixed building rejects map edge",()=>{const e=new TemplateEditorEngine();e.addType({...type,width:2,height:2});assert.throws(()=>e.addBuilding({name:"A",typeId:type.id,x:0,y:0}))});
test("fixed range create, edit, overlap, erase and delete",()=>{const e=new TemplateEditorEngine();const a=e.addRange({kind:"allowed",color:"#123456",cells:[[0,0],[1,1]]});e.editRange(a.id,{kind:"blocked",color:"#abcdef"});assert.throws(()=>e.addRange({kind:"allowed",color:"#123456",cells:[[1,1]]}));assert.equal(e.eraseRangeCells([[0,0]]),1);assert.deepEqual(e.getDocument().fixedRanges[0].cells,[[1,1]]);e.deleteRange(a.id);assert.equal(e.getDocument().fixedRanges.length,0)});
test("invalid template load preserves current document",()=>{const e=new TemplateEditorEngine();e.addType(type);assert.throws(()=>e.loadTemplate({...emptyTemplate(),version:9}));assert.equal(e.getDocument().fixedBuildingTypes[0].id,type.id)});
test("export is canonical and transient controller state is excluded",()=>{const e=new TemplateEditorEngine();e.addType(type);const out=e.exportTemplate();assert.deepEqual(parseTemplate(out).fixedBuildingTypes.map(x=>x.id),[type.id]);assert.equal("preview" in out,false)});
test("fixed type/building/range changes support undo and redo",()=>{const e=new TemplateEditorEngine(),h=createHistory();h.clear({saved:true});const b=createTemplateBuildingController({engine:e,history:h}),r=createTemplateRangeController({engine:e,history:h});b.mutate(()=>e.addType(type),"type");b.selectPalette(type.id);b.commitAt(0,0,{name:"A"});r.startCreate({kind:"allowed",color:"#123456"});r.click([2,2]);r.click([3,3]);r.commit();assert.equal(e.getDocument().fixedRanges.length,1);b.undo();assert.equal(e.getDocument().fixedRanges.length,0);b.redo();assert.equal(e.getDocument().fixedRanges.length,1)});
test("isomap conversion groups only used type+size combinations and preserves data/view",()=>{const input=source({buildings:Array.from({length:10},(_,i)=>({id:`b${i}`,name:`건물${i}`,type_id:"type-01",x:20+i*2,y:20+i*2,width:2,height:2,affiliation:"",locked:false}))});const out=convertDocumentToTemplate(input),p=parseTemplate(out);assert.equal(p.fixedBuildingTypes.length,1);assert.equal(p.fixedBuildingTypes[0].id,"type-01-2x2");assert.equal(p.fixedBuildings.length,10);assert.equal(p.fixedBuildings[3].name,"건물3");assert.equal(p.fixedBuildings[3].x,26);assert.deepEqual(p.view,{centerX:39,centerY:41,zoom:.8695652173913043})});
test("isomap conversion separates same type used at 1x1 and 2x2",()=>{const p=parseTemplate(convertDocumentToTemplate(source({buildings:[{id:"a",name:"A",type_id:"type-01",x:0,y:0,width:1,height:1},{id:"b",name:"B",type_id:"type-01",x:4,y:4,width:2,height:2}]})));assert.equal(p.fixedBuildingTypes.length,2);assert.notEqual(p.fixedBuildings[0].typeId,p.fixedBuildings[1].typeId)});
test("isomap conversion merges fixed data, remaps IDs and converts ranges",()=>{const collidingType={...type,id:"type-01"};const p=parseTemplate(convertDocumentToTemplate(source({buildings:[{id:"user",name:"U",type_id:"type-01",x:4,y:4,width:1,height:1}],ranges:[{id:"r",kind:"allowed",color:"#123456",locked:true,cells:[[2,2]]}],fixed_building_types:[collidingType],fixed_buildings:[{id:"fixed",name:"F",type_id:collidingType.id,x:0,y:0}],fixed_ranges:[{id:"r",kind:"blocked",color:"#654321",cells:[[0,2]]}]})));assert.equal(p.fixedBuildings.length,2);assert.notEqual(p.fixedBuildingTypes[0].id,p.fixedBuildingTypes[1].id);assert.equal(p.fixedRanges.length,2);assert.notEqual(p.fixedRanges[0].id,p.fixedRanges[1].id)});
test("isomap conversion rejects collisions and invalid input",()=>{const input=source({buildings:[{id:"u",name:"U",type_id:"type-01",x:0,y:0,width:1,height:1}],fixed_building_types:[type],fixed_buildings:[{id:"f",name:"F",type_id:type.id,x:0,y:0}]});assert.throws(()=>convertDocumentToTemplate(input));assert.throws(()=>convertDocumentToTemplate({...input,format:"bad"}))});
test("renderer template mode is opt-in so ordinary fixed immutability contract remains",async()=>{const text=await (await import("node:fs/promises")).readFile(new URL("../editor-renderer.js",import.meta.url),"utf8");assert.match(text,/editableFixed = false/);assert.match(text,/!building\.fixed \|\| editableFixed/)});
test("template editor keeps its admin gate while server integration stays in its module",async()=>{const fs=await import("node:fs/promises"),html=await fs.readFile(new URL("../../template-editor/index.html",import.meta.url),"utf8"),app=await fs.readFile(new URL("../../template-editor/template-editor-app.js",import.meta.url),"utf8");assert.match(html,/admin-auth\.js/);assert.match(app,/S967AdminAuth\.validate/);assert.match(app,/S967AdminAuth\.getToken/);assert.match(html,/template-editor-app\.js/)});
